### ISSUE TITLE
Cursor with Amazon Redshift

### ISSUE THREAD

**Issue by kruser** [brianc/node-pg-cursor#14]
Has anybody used this with Amazon Redshift? I use the pg module with great success and have tried this cursor module as well. Everything functions and I can read from the cursor but the entire result set is loaded into RAM when the query is executed so it doesn't solve my problem.

**Comment by Claytonious** [comment]
Seeing the same thing - entire result set is returned from Redshift.

**Comment by Claytonious** [comment]
But, interestingly, this only seems to be a problem against Node 4.x. It *does* appear to work with Redshift under Node 0.10.36.

**Comment by JvrBaena** [comment]
Same here.

I have noticed this error using the `pg-query-stream` package, which uses this package underneath to stream results. When the result set is too big, the speed at which the stream emits results back is affected.

I'm struggling to understand the Cursor class though (I don't have much experience with Redshift/Postgre) trying to debug why is this happening.

**Comment by jjmartin** [comment]
omg - is that what the issue is? .10 vs 4.3.2?    i've been banging my head on this ...

**Comment by jjmartin** [comment]
i can't seem to duplicate the same behavior from .10 to 4.3.2    so it might just be a change in redshift if one of you saw it working before

**Comment by greghart** [comment]
Delved into this a bit as I've been having the same issue -- basically Redshift seems to ignore the `Rows` argument of the execute message on the extended query mode of the protocol (https://www.postgresql.org/docs/devel/static/protocol-flow.html#PROTOCOL-FLOW-EXT-QUERY). I can't seem to find any documentation on Redshift's support for this unfortunately. 

Manually setting up a cursor using DESCRIBE and FETCH seems like the only viable workaround to me right now

**Comment by serenitygrant** [comment]
Have there been any updates to this? I'm using the pg-query-stream package to ETL from redshift and I do notice that quite a bit of memory is being used. Is this because the cursor isn't working correctly and all rows are being loaded into memory initially?

**Comment by joeflateau** [comment]
To those looking for a solution, I got the following to work:

        const cursorName = "cursor" + Date.now();

        client
          .query(
            ` begin;
              declare ${cursorName} cursor for
              select *
              from events
              group by label, name, category;`
          )
          .then(() => {
            let currentPage = 0;
            const readPage = size => {
              client
                .query(`fetch forward ${size} from ${cursorName};`)
                .then(result => {
                  const rows = result.rows;

                  currentPage++;
                  console.log(
                    `asked for ${size} got ${rows.length} page ${currentPage}`
                  );

                  if (rows.length === 0) {
                    client.query(`close ${cursorName}`);

                    return client
                      .query(`commit`)
                      .then(() => client.end())
                      .then(() => resolve());
                  }

                  SomeCollection.collection
                    .bulkWrite(
                      rows.map(r => ({
                        updateOne: {
                          filter: {
                            some:'filter'
                          },
                          replacement: {
                            $set: {
                              some:'filter',
                              ["values." + r.name]: {
                                distinct_session: Number(r.distinct_session),
                                distinct_user: Number(r.distinct_user),
                                sum_value: Number(r.sum_value),
                                count: Number(r.count)
                              }
                            }
                          },
                          upsert: true
                        }
                      })),
                      { ordered: false }
                    )
                    .then(() => {
                      readPage(1000);
                    })
                    .catch(err => reject(err));
                });
            };

            readPage(100);
          });

**Comment by kmportal** [comment]
Hi joeflateau

I am getting an error using this implementation. I cursor not found error.

2018-03-26T10:10:04.373Z	da49df69-30dd-11e8-87c3-0965b2552c36	Unhandled rejection error: cursor "eventdata" does not exist
at Connection.module.exports.Connection.parseE (/var/task/dist/lambda.js:35294:11)
at Connection.module.exports.Connection.parseMessage (/var/task/dist/lambda.js:35118:17)
at Socket.<anonymous> (/var/task/dist/lambda.js:34856:22)
at emitOne (events.js:96:13)
at Socket.emit (events.js:188:7)
at readableAddChunk (_stream_readable.js:176:18)
at Socket.Readable.push (_stream_readable.js:134:10)
at TCP.onread (net.js:547:20)
From previous event:

**Comment by joeflateau** [comment]
@kmportal you'd have to provide more information, including a code example. The fact that it's looking for a cursor named "eventdata" means you've modified this code a bit. This could would only ever have a cursor named `cursor_${now}_${random}`

**Comment by kmportal** [comment]
var query = "begin ; declare eventData cursor for select * from events_na; "

             pageThroughLargeResult(redshiftClient, query);

             function pageThroughLargeResult(redshiftClient, query) {
                             return redshiftClient.query(query)
                               .then(() => {
                                 let currentPage = 0;
                                 console.log("inside???????????");
                                 const readPage = size => {
                                   console.log("ok now what????????");
                                   return redshiftClient.query("fetch forward 1 from eventData")
                                     .then(result => {
                                       console.log("fetch???????????");
                                       const rows = result.rows;

                                       currentPage++;
                                       console.log("asked for ${1} got " , rows.length);

                                       // never call pageCallback with zero rows
                                       return (rows.length > 0
                                         ? pageCallback(rows)
                                         : Promise.resolve()).then(() => {
                                         if (rows.length < size) {
                                           return redshiftClient
                                             .query("close eventData;")
                                             .then(() => redshiftClient.query("commit"));
                                         }
                                         return readPage(1000);
                                       });
                                     });
                                 };

                                 return readPage(100);
                               });
                           }

                          
        } catch(e) {
            console.log(e);
            res.status(500).send('failed');
        }


}) ;

**Comment by joeflateau** [comment]
@kmportal This isn't really a Q/A forum for specific usages like this. I'm not sure why you found it necessary to make the changes you did to the code, but you shouldn't have, for example: pageCallback is no longer defined in your code, strings aren't built properly, etc. Just use the function that I pasted above. You're also not handing the promise properly and the function shouldn't be defined in the route handler.

**Comment by kmportal** [comment]
@joeflateau : Well, thanks a lot for your help. 1) I found necessary because I believed you wrote a generic/flexible/re-usable code and you no where mentioned that it is a specific code. But now you claim its not  generic and which acc to me is not a right practice.  Also I have to use the concept differently. How can you ask me simply copy-paste.  My primary interest was knowing the concept of it rather than coding standards. 2) pageCallBack IS defined in the code(but **not pasted** here due to info security clauses I cannot share and also it didn't seem to me an issue) 3) Your answer doesn't takes into account the error log I provided. 4) I know this is not a Q/A forum and so I didn't force/compel/pester you to answer. 

Anyways I Thank you so much for your help and support. Good bye and good luck.

**Comment by jafl** [comment]
I think I found the issue:  Redshift wants a portal name.

When I use an empty portal name (the current code), my lambda exceeds the maximum allotted memory of 128MB and fails - long before the 5 minute timeout.

When I pass a non-empty portal name to the connection's bind(), describe(), and execute() functions, my lambda uses only 30MB.

I will open a PR in a few minutes.
